// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type GormIoGormDeletedAt struct {
	Time  time.Time `json:"Time"`
	Valid bool      `json:"Valid"`
}

type Mutation struct {
}

type PageInfo struct {
	EndCursor   *string `json:"endCursor,omitempty"`
	HasNextPage *bool   `json:"hasNextPage,omitempty"`
	HasPrevPage *bool   `json:"hasPrevPage,omitempty"`
	StartCursor *string `json:"startCursor,omitempty"`
}

type Query struct {
}
