import fs from "fs";

import { docPath, ensureDirectoryExistence, loader } from "./loader";

import { queries } from "@/lib/queries";

const init = () => {
  ensureDirectoryExistence(docPath);
  const results = [loader(queries, "main")];

  const info = `# This file is auto generated don't modify it manually
# generated by pnpm gql:parse
`;

  fs.writeFileSync(
    `${docPath}/queries.graphql`,
    `${info}\n${results.join("\n\n")}`,
  );
};

init();
